language: minimal

services:
  - docker

env:
  - OS=ubuntu:19.04

before_install:
  - docker pull $OS

script:
  - docker run
      --volume $PWD:/host
      --workdir /host/continuous-integration
      $OS
      bash -c "./setup.sh &&
               ./lint.sh"
